version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "17"
  language_version = "1.9"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "test-coverage"
