name: Build Project

on:
  push:
    branches: ["main"]
    tags: ["stable"]

  
jobs:
  build-prod:
    if: github.ref == 'refs/tags/stable'
    runs-on: self-hosted

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build FontEnd Project
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: Install FrontEnd Dependencies
        run: |
          cd Frontend
          npm install

      - name: Build FrontEnd Project
        run: |
          cd Frontend
          npm run build


      - name: Move static files into Spring Boot Ressources Folder
        run: |
          mkdir -p Backend/src/main/resources/static
          cp -R Frontend/dist/* Backend/src/main/resources/static/
      

      - name: Check static files
        run: |
          ls -al Backend/src/main/resources/static

      # Build BackEnd Project
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      
      - name: Build and Test with Maven
        run: |
          cd Backend
          mvn clean test verify package -B --file pom.xml

      
      - name: Build & Push Docker Image
        run: |
          docker login --username ${{ secrets.GH_U }} --password ${{ secrets.GH_P }} ghcr.io
          docker build -t ghcr.io/structsure-lastproject/structsure/structsure:stable -f Backend/Dockerfile .
          docker push ghcr.io/structsure-lastproject/structsure/structsure:stable



  build-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build FontEnd Project
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: Install FrontEnd Dependencies
        run: |
          cd Frontend
          npm install

      - name: Build FrontEnd Project
        run: |
          cd Frontend
          npm run build


      - name: Move static files into Spring Boot Ressources Folder
        run: |
          mkdir -p Backend/src/main/resources/static
          cp -R Frontend/dist/* Backend/src/main/resources/static/
      

      - name: Check static files
        run: |
          ls -al Backend/src/main/resources/static

      # Build BackEnd Project
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      

      - name: Build and Test with Maven
        run: |
          cd Backend
          mvn clean test verify package -B --file pom.xml


      - name: Build & Push Docker Image
        run: |
          docker login --username ${{ secrets.GH_U }} --password ${{ secrets.GH_P }} ghcr.io
          docker build -t ghcr.io/structsure-lastproject/structsure/structsure:latest -f Backend/Dockerfile .
          docker push ghcr.io/structsure-lastproject/structsure/structsure:latest





           
      
      
