name: Test FrontEnd SolidJS / BackEnd Spring Boot

on:
  push:
    branches: ["main"]

jobs:
  deepsource:
    runs-on: self-hosted
    env:
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.13.0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"
        cache: maven

    - name: Run Java Tests
      run: |
        cd Backend
        mvn clean test --file pom.xml


    - name: Run Tests and Generate Coverage
      run: | 
        cd Frontend
        npm install
        npm run coverage


    - name: Report test-coverage to DeepSource
      run: |
        cd Frontend

        # Send the report to DeepSource
        ${{ secrets.DEEPSOURCE_LOCATION }}/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/lcov.info

        cd ../Backend

        ${{ secrets.DEEPSOURCE_LOCATION }}/deepsource report --analyzer test-coverage --key java --value-file target/site/jacoco/jacoco.xml