name: Test FrontEnd SolidJS / BackEnd Spring Boot

on:
  push:
    branches: ["main"]

jobs:
  deepsource:
    runs-on: self-hosted
    env:
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Tests and Generate Coverage
      run: docker run --rm -v ${{ secrets.FRONTEND_PATH }}:/app -w /app --user 1001 node:22-bullseye-slim sh -c "npm install && npm run coverage"

    - name: Run Java Tests
      run: |
        cd Backend
        mvn test

    - name: Report test-coverage to DeepSource
      run: |
        # Install the CLI
        curl https://deepsource.io/cli | sh

        cd ../Frontend

        # Send the report to DeepSource
        ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/lcov.info

        cd ../Backend

        ./bin/deepsource report --analyzer test-coverage --key java --value-file target/site/jacoco/jacoco.xml